replicaCount: 2

image:
  pullPolicy: Always

resources:
  limits:
    cpu: 250m
    memory: 512Mi

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]